name = "where-am-i"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-13"

# Configuración para despliegue sin build (usa archivos pre-construidos)
# No incluye la sección [build] para evitar errores de cargo

# Environment variables for CORS configuration
[vars]
# CORS allowed origins - configure for production security
# Default: "*" allows all origins (NOT recommended for production)
# Production example: "https://myapp.com,https://www.myapp.com,https://api.myapp.com"
# Development example: "http://localhost:3000,http://localhost:8080"
CORS_ALLOWED_ORIGINS = "*"
